[package]
name = "mldata"
version = "0.1.0"
authors = ["mbilling"]

[dependencies]
app_dirs = "1.2"
arff = { git = "https://github.com/mbillingr/arff.git" }
ndarray = "0.11"
num = "0.1"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"